version: "3.3"

services:

  maven_build:
    image: dgomes_websockets:0.1
    build:
      context: ./ws-backend
      dockerfile: ./dockerfiles/maven_build/DockerFile

  rabbitmq:
    build:
      context: ./ws-backend
      dockerfile: ./dockerfiles/rabbitmq_stomp/DockerFile
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    ports:
      - "61613:61613"
    restart: on-failure
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "61613" ]
      timeout: 5s
      retries: 1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
        
  spring_run:
    build:
      context: ./ws-backend
      dockerfile: ./dockerfiles/spring_run/DockerFile
    command: java -jar dgomes_app.jar
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  nginx:
    image: nginx:1.13.3
    container_name: nginx
    restart: on-failure
    volumes:
      - ./ws-frontend:/usr/share/nginx/html
      #- ./nginx:/etc/nginx/sites_enabled
    ports:
      - 80:80

volumes:
  rabbitmq_data:
