FROM rabbitmq:3-management

RUN rabbitmq-plugins enable rabbitmq_stomp
RUN rabbitmq-plugins enable rabbitmq_web_stomp
RUN rabbitmq-plugins enable --offline rabbitmq_management
ENV RABBITMQ_SERVER_START_ARGS -eval error_logger:tty(true).

EXPOSE 61613
EXPOSE 15674
EXPOSE 15672